server:
  port: 8087

spring:
  config:
    import:
      - classpath:waitlist-core-application.yml
  application:
    name: waitlist-api
  profiles:
    include: common-services

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always