server:
  port: 8082
debug: true
spring:
  config:
    import:
      - classpath:prompts-core-application.yml
  application:
    name: prompts-api
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.security: TRACE
    org.springframework.boot.autoconfigure: INFO
    org.springframework.context.annotation: INFO
    org.springframework.ai: DEBUG
    com.batchprompt: DEBUG
    org.flywaydb: TRACE
    org.hibernate: INFO
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type: TRACE

services:
  name: prompts-api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
