services:

   postgres:
      image: postgres:latest
      environment:
         POSTGRES_PASSWORD: "batchprompt"
         POSTGRES_DB: "batchprompt"
         POSTGRES_USER: "batchprompt"
      ports:
         - "5432:5432"
      command:
         - "postgres"
         - "-c"
         - "max_connections=250"
      volumes:
         - postgres:/var/lib/postgresql/data
   nginx-gateway:
      build:
         context: ./nginx
         dockerfile: Dockerfile
      extra_hosts:
         - "host.docker.internal:host-gateway"         
      ports:
      - "8081:8081"     
   minio:
      image: minio/minio
      ports:
         - "9000:9000"
         - "9001:9001"
      environment:
         MINIO_ROOT_USER: batchprompt
         MINIO_ROOT_PASSWORD: batchprompt
      volumes:
         - minio-data:/data
      command: server /data --console-address ":9001"

volumes:
   postgres:
   minio-data:

