server:
  port: 8084
debug: true
spring:
  config:
    import:
      - ${HOME}/.batchprompt/local.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/batchprompt
    username: batchprompt
    password: batchprompt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: jobs
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: jobs
    create-schemas: true
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.issuer-uri}
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.security: TRACE
    org.springframework.boot.autoconfigure: INFO
    org.springframework.context.annotation: INFO
    com.batchprompt: DEBUG
    org.flywaydb: TRACE
    org.hibernate: INFO
  file:
    name: logs/jobs.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/jobs-%d{yyyy-MM-dd}.%i.log
      clean-history-on-start: false
      max-file-size: 10MB
      total-size-cap: 1GB        

services:
  files:
    url: http://localhost:8083
  prompts:
    url: http://localhost:8082

rabbitmq:
  exchange:
    name: batchprompt-exchange
  queue:
    jobs:
      name: jobs-queue
  routing:
    jobs:
      key: jobs.routing.key


