server:
  port: 8082
debug:true:
spring:
  application:
    name: prompts-service
  config:
    import:
      - ${HOME}/.batchprompt/local.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/batchprompt
    username: batchprompt
    password: batchprompt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: prompts
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: prompts
    create-schemas: true
    baseline-on-migrate: true
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.security: TRACE
    org.springframework.boot.autoconfigure: INFO
    org.springframework.context.annotation: INFO
    org.springframework.ai: DEBUG
    com.batchprompt: DEBUG
    org.flywaydb: TRACE
    org.hibernate: INFO
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type: TRACE

services:
  name: prompts-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
