server:
  port: 8083
debug: true
spring:
  config:
    import:
      - ${HOME}/.batchprompt/local.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/batchprompt
    username: batchprompt
    password: batchprompt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: files
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: files
    create-schemas: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.issuer-uri}
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.security: TRACE
    org.springframework.boot.autoconfigure: INFO
    org.springframework.context.annotation: INFO
    com.batchprompt: DEBUG
    org.flywaydb: TRACE
    org.hibernate: INFO
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type: TRACE

minio:
  endpoint: http://localhost:9000
  access-key: batchprompt
  secret-key: batchprompt
  bucket: batchprompt

rabbitmq:
  exchange:
    name: batchprompt-exchange
  queue:
    files:
      name: files-queue
  routing:
    files:
      key: files.routing.key
