# Application configuration
spring:
  main:
    banner-mode: OFF
  application:
    name: batchprompt-cli
  config:
    import:
      - ${HOME}/.batchprompt/local.yml
      
# Logging
logging:
  level:
    root: OFF
