server:
  port: 8086
debug: true
spring:
  application:
    name: notifications-api
  config:
    import:
      - ${HOME}/.batchprompt/local.yml
      - ${HOME}/.batchprompt/logging.yml

  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

