spring:
  config:
    import:
      - ${HOME}/.batchprompt/local.yml
      - ${HOME}/.batchprompt/logging.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/batchprompt
    username: batchprompt
    password: batchprompt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: users
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: users
    create-schemas: true
    baseline-on-migrate: true


