spring:
  config:
    import:
      - ${HOME}/.batchprompt/local.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/batchprompt
    username: batchprompt
    password: batchprompt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: jobs
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: jobs
    create-schemas: true
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: batchprompt
    password: batchprompt
    virtual-host: /

services:
  name: jobs-service
  files:
    url: ${FILES_SERVICE_URL:http://localhost:8083}
  prompts:
    url: ${PROMPTS_SERVICE_URL:http://localhost:8082}

rabbitmq:
  exchange:
    name: batchprompt-exchange
  queue:
    job-output:
      name: job-output-queue
      routing-key: job-output-queue

# Model configuration
openai:
  api-key: ${OPENAI_API_KEY:your-openai-api-key}

# Google configuration
google:
  api-key: ${GOOGLE_API_KEY:your-google-api-key}

# AWS configuration
aws:
  access-key: ${AWS_ACCESS_KEY:your-aws-access-key}
  secret-key: ${AWS_SECRET_KEY:your-aws-secret-key}
  region: ${AWS_REGION:us-east-1}

# Models configuration
models:
  supported:
    - name: gpt-4o
      provider: OPENAI
      queue: gpt4o-queue
    - name: gpt-4
      provider: OPENAI
      queue: gpt4-queue
    - name: gpt-3.5-turbo
      provider: OPENAI
      queue: gpt35-queue
    - name: deepseek-r1
      provider: AWS
      queue: deepseek-queue
      properties:
        arn: arn:aws:bedrock:us-east-1:187419035811:inference-profile/us.deepseek.r1-v1:0
    - name: gemini-2.0-flash
      provider: GOOGLE
      queue: gemini-flash-queue
    - name: gemini-2.0-flash-lite
      provider: GOOGLE
      queue: gemini-flash-lite-queue
    - name: gemini-2.5-pro
      provider: GOOGLE
      queue: gemini-pro-queue
    - name: gemini-2.5-flash
      provider: GOOGLE
      queue: gemini-flash-2-5-queue
    - name: gemini-1.5-flash
      provider: GOOGLE
      queue: gemini-flash-1-5-queue
    - name: gemini-1.5-pro
      provider: GOOGLE
      queue: gemini-pro-1-5-queue

# Worker configuration
workers:
  configurations:
    - queue: gpt4o-queue
      concurrentRequests: 5
      rateLimit: 20  # Requests per minute
    - queue: gpt4-queue
      concurrentRequests: 3 
      rateLimit: 10  # Requests per minute
    - queue: gpt35-queue
      concurrentRequests: 10
      rateLimit: 60  # Requests per minute
    - queue: deepseek-queue
      concurrentRequests: 5
      rateLimit: 30  # Requests per minute
    - queue: gemini-flash-queue
      concurrentRequests: 8
      rateLimit: 50  # Requests per minute
    - queue: gemini-flash-lite-queue
      concurrentRequests: 10
      rateLimit: 60  # Requests per minute
    - queue: gemini-pro-queue
      concurrentRequests: 5
      rateLimit: 30  # Requests per minute
    - queue: gemini-flash-2-5-queue
      concurrentRequests: 8
      rateLimit: 50  # Requests per minute
    - queue: gemini-flash-1-5-queue
      concurrentRequests: 8
      rateLimit: 50  # Requests per minute
    - queue: gemini-pro-1-5-queue
      concurrentRequests: 5
      rateLimit: 30  # Requests per minute
