spring:
  config:
    import:
      - ${HOME}/.batchprompt/local.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/batchprompt
    username: batchprompt
    password: batchprompt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: files
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: files
    create-schemas: true
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.issuer-uri}
minio:
  endpoint: http://localhost:9000
  access-key: batchprompt
  secret-key: batchprompt
  bucket: batchprompt
